name: "Integration test (POSTGRES)"

on:
  push:
jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest

        env:
          POSTGRES_DB: ${{ secrets.DATABASE }}
          POSTGRES_PASSWORD: ${{ secrets.PD }}
          POSTGRES_ROOT_HOST: ${{ secrets.ROOT_HOST }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Change work directory
        working-directory: ./whatsApp
        run: chmod +x ./gradlew 

      - name: Print Gradle Version
        run: ./gradlew --version        

      - name: Build with Gradle
        working-directory: ./whatsApp
        run: ./gradlew build

      - name: create and configure
        run: |
          touch .env
          echo "db_port=${{ secrets.PORT }}" >> .env
          echo "db_username=${{ secrets.USER }}" >> .env
          echo "db_password=${{ secrets.PD }}" >> .env
          echo "db_name"=${{ secrets.DATABASE }} >> .env

          

          





