name: "Integration test (POSTGRES)"

on:
  push:
jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest

        env:
          POSTGRES_DB: ${{ secrets.DATABASE }}
          POSTGRES_PASSWORD: ${{ secrets.PD }}
          POSTGRES_ROOT_HOST: ${{ secrets.ROOT_HOST }}
          echo db_host: ${{ secrets.HOST }}
          echo db_port: ${{ secrets.PORT }}
          echo db_name: ${{ secrets.DATABASE }}
          echo db_username: ${{ secrets.USER }}
          echo db_password: ${{ secrets.PD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Change work directory
        working-directory: ./whatsApp
        run: chmod +x ./gradlew 

      - name: Print Gradle Version
        working-directory: ./whatsApp
        run: ./gradlew --version 

      - name: Build with Gradle
        working-directory: ./whatsApp
        run: ./gradlew build

      

          

          





