name: "Integration test (POSTGRES)"

on:
  push:
jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest

        env:
          POSTGRES_DB: chatapplication
          POSTGRES_PASSWORD: priyanka9167
          POSTGRES_ROOT_HOST: priyanka
          
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check PostgreSQL Connection
        run: |
          # Add your commands to check the connection or perform tests against PostgreSQL
          # For example:
          psql -h localhost -U $db_username -d $db_name -c 'SELECT version();'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Change work directory
        working-directory: ./whatsApp
        run: chmod +x ./gradlew 

      - name: Print Gradle Version
        working-directory: ./whatsApp
        run: ./gradlew --version

      - name: Build with Gradle
        working-directory: ./whatsApp
        run: ./gradlew build

      

          

          





