name: "Integration test (POSTGRES)"

on:
  push:
    branches:
      - testing
jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest

        env:
          POSTGRES_DB: ${{ secrets.DATABASE }}
          POSTGRES_PASSWORD: ${{ secrets.PD }}
          POSTGRES_USER: ${{ secrets.USER }}

        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List PostgreSQL Users
        run: |
          echo "SELECT usename FROM pg_user;" | psql -h localhost -U priyanka -d ${{ secrets.DATABASE }}
        env:
          PGPASSWORD: ${{ secrets.PD }}

      - name: Setup config
        working-directory: ./whatsApp
        run: |
          mkdir config
          echo 'spring.datasource.url=jdbc:postgresql://localhost:5432/{{ secrets.DATABASE }}' > config/application.properties
          echo 'spring.datasource.username=${{ secrets.USER }}' >> config/application.properties
          echo 'spring.datasource.password=${{ secrets.PD }}' >> config/application.properties


      - name: Build with Gradle
        working-directory: ./whatsApp
        run: ./gradlew build

      - name: Run Tests
        working-directory: ./whatsApp
        run: ./gradlew test



      - name: Save Jar file
        uses: actions/upload-artifact@v3
        with:
          name: demo-0.0.1-SNAPSHOT
          path: ./whatsApp/build/libs/whatsApp-0.0.1-SNAPSHOT.jar





          

          





