name: "Integration test (POSTGRES)"

on:
  push:
jobs:
  connect-remote:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest

        env:
          POSTGRES_DB: chatapplication
          POSTGRES_PASSWORD: priyanka9167
          POSTGRES_USER: priyanka
          
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
     

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup config
        working-directory: ./whatsApp
        run: |
          mkdir config

          echo 'spring.datasource.url=jdbc:postgresql://postgres:5432/chatapplication' > config/application.properties    

      - name: Build with Gradle
        working-directory: ./whatsApp
        run: ./gradlew build

      - name: Update dependency graph
        uses: snyk/actions/gradle@8
        with:
          target-file: ./whatsApp/build.gradle 

      - name: Build Jar file
        working-directory: ./whatsApp
        run:  build-jar 

      - name: Save Jar file
        uses: actions/upload-artifact@v3
        with:
          name: demo-0.0.1-SNAPSHOT
          path: ./whatsApp/build/libs/demo-0.0.1-SNAPSHOT.jar        

      

          

          





